[features]
seeds = true
skip-lint = false
[programs.devnet]
agora_court = "7XVbwGZara96w6qiw2VuhaPUAoNQyyVDHxN6sC4YHY3N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kevinz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
lint = "cargo dylint --all --workspace"