[features]
seeds = false
skip-lint = false

[programs.devnet]
agora_court = "ABkQZCq2qh32X75A5FjaT8FGRWEqujPiBV3wJZEmzuEX"

[programs.localnet]
agora_court = "ABkQZCq2qh32X75A5FjaT8FGRWEqujPiBV3wJZEmzuEX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/vsiva360/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
basic = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/basic.test.ts"
lint = "cargo dylint --all --workspace"