[features]
seeds = false
skip-lint = false

[programs.devnet]
agora_court = "Benri2piS4b4h5S54uaMRybuhhZtbM4L3zofhd3Y9FXv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/vsiva360/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initializecourt = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-court.test.ts"
initializedispute = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-dispute.test.ts"
lint = "cargo dylint --all --workspace"