[features]
seeds = false
skip-lint = false

[programs.devnet]
agora_court = "xmLz8CwRQceUVYdHmPb72xASFE2eYYhsKUcetZbvRd7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/vsiva360/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
lint = "cargo dylint --all --workspace"