[features]
seeds = false
skip-lint = false

[programs.devnet]
agora_court = "Benri2piS4b4h5S54uaMRybuhhZtbM4L3zofhd3Y9FXv"
demo_tokens = "8oxb3Kg4kda7LCJoSUVHAZhoqWjmBiLnGZeCyUkJJ22L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/vsiva360/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initcourt = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-court.test.ts"
initdispute = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-dispute.test.ts"
initrecord = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize-record.test.ts"
createcourt = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-court.test.ts"
demoinit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/demo-initialize.test.ts"
lint = "cargo dylint --all --workspace"